/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    users: User;
    services: Service;
    reviews: Review;
    portfolios: Portfolio;
    categories: Category;
    solutions: Solution;
    technologies: Technology;
    industries: Industry;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    portfolios: PortfoliosSelect<false> | PortfoliosSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'vi') | ('en' | 'vi')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'vi';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    settings: {
      /**
       * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
       */
      bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
      /**
       * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
       */
      bgGradient?: string | null;
      /**
       * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
       */
      bgColor?: string | null;
      /**
       * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
       */
      bgImage?: (number | null) | Media;
      /**
       * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
       */
      bgRepeat?: boolean | null;
      /**
       * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
       */
      bgSize?: ('contain' | 'cover' | 'custom') | null;
      /**
       * Enter a value in pixels or percent (e.g., 70px, 50%)
       */
      bgSizeCustom?: string | null;
      /**
       * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
       */
      bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
      /**
       * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
       */
      bgAttachment?: ('scroll' | 'fixed') | null;
      /**
       * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
       */
      padding?: string | null;
      /**
       * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
       */
      maxWidth?: string | null;
      /**
       * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
       */
      borderRadius?: string | null;
      type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
      /**
       * Margin format: "top right bottom left" (e.g., "16px 24px 16px 24px"). Applies to media. Each value sets margin for one side, in order: top, right, bottom, left.
       */
      margin?: string | null;
      /**
       * Width of the media (e.g., "100%", "400px", "40vw"). Accepts any valid CSS width value.
       */
      width?: string | null;
      /**
       * Show the media on mobile devices.
       */
      showMobile?: boolean | null;
      /**
       * Border radius of the media (e.g., "16px", "2rem", "50%"). Rounds the corners of the media.
       */
      mediaBorderRadius?: string | null;
    };
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label?: string | null;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'outline' | 'link' | 'secondary') | null;
      /**
       * Choose how the link position should be.
       */
      position?: ('center' | 'right') | null;
    };
    media?: (number | null) | Media;
  };
  layout?:
    | (
        | CallToActionBlock
        | ContentBlock
        | MediaBlock
        | ArchiveBlock
        | FormBlock
        | FeatureBlock
        | MediaContentBlock
        | MapsBlock
        | CarouselBlock
        | IListBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  type?: ('blog' | 'service' | 'technology') | null;
  icon?: (number | null) | Media;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
  };
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
          /**
           * Choose how the link position should be.
           */
          position?: ('center' | 'right') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
  };
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline' | 'link' | 'secondary') | null;
          /**
           * Choose how the link position should be.
           */
          position?: ('center' | 'right') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
  };
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
  };
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label?: string | null;
  };
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: ('posts' | 'services' | 'reviews' | 'portfolios') | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
  };
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            placeHolder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            placeHolder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            placeHolder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            placeHolder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            placeHolder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlock".
 */
export interface FeatureBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
    layout?: ('3-columns' | '4-columns' | '5-columns') | null;
  };
  items?:
    | {
        media?: (number | null) | Media;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaContentBlock".
 */
export interface MediaContentBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
    /**
     * Space between media and content elements (CSS units, e.g., 24px, 2rem). Default: 24px.
     */
    gap?: string | null;
    /**
     * Choose the order of content and media within this block. "Media + Content" displays the media first, followed by the content; "Content + Media" reverses the order.
     */
    alignment?: ('contentMedia' | 'mediaContent') | null;
    /**
     * Select the proportional layout of Content and Media within this block.
     */
    layout?: ('1/2' | '1/4' | '2/5' | '1/3' | '3/5' | '2/3' | '3/4' | 'full') | null;
    /**
     * Margin format: "top right bottom left" (e.g., "16px 24px 16px 24px"). Applies to media. Each value sets margin for one side, in order: top, right, bottom, left.
     */
    margin?: string | null;
    /**
     * Width of the media (e.g., "100%", "400px", "40vw"). Accepts any valid CSS width value.
     */
    width?: string | null;
  };
  media?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  enableButtonDirect?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline' | 'link' | 'secondary') | null;
    /**
     * Choose how the link position should be.
     */
    position?: ('center' | 'right') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapsBlock".
 */
export interface MapsBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
    /**
     * Map width in pixels (px)
     */
    width?: number | null;
    /**
     * Map height in pixels (px)
     */
    height?: number | null;
  };
  title?: string | null;
  specificAddress?: string | null;
  /**
   * Latitude coordinate of the location
   */
  latitude?: number | null;
  /**
   * Longitude coordinate of the location
   */
  longitude?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
    type?: 'content' | null;
    /**
     * If checked, the carousel will extend to the full width of the viewport, overflowing the container.
     */
    fullWidth?: boolean | null;
  };
  title?: string | null;
  subtitle?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label?: string | null;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline' | 'link' | 'secondary') | null;
    /**
     * Choose how the link position should be.
     */
    position?: ('center' | 'right') | null;
  };
  slides?:
    | {
        direction?: ('slide-to-right' | 'slide-to-left') | null;
        slidesPerViewD?: number | null;
        slidesPerViewM?: number | null;
        autoPlay?: boolean | null;
        enableArrow?: boolean | null;
        items?:
          | {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IListBlock".
 */
export interface IListBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
    /**
     * Choose how many columns to show your list: 2 columns, 3 columns, or 4 columns. Pick what fits your content best.
     */
    layout?: ('1-cols' | '2-cols' | '3-cols' | '4-cols') | null;
    /**
     * Choose the style for your list: "Icon Content" displays items with icons and text, while "Stats Highlight" shows statistical highlights with numbers or key data.
     */
    type?: ('icon-content' | 'stats-highlight') | null;
    /**
     * Width of the icon in pixels (e.g. 24px, 2rem, ...). Leave blank for 24px.
     */
    iconSize?: string | null;
  };
  title?: string | null;
  subtitle?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  items?:
    | {
        iconContent?: {
          icon?: (number | null) | Media;
          content?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
        };
        statsHighlight?: {
          value: string;
          label: string;
          subLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'listBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  icon: number | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  image: number | Media;
  content?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios".
 */
export interface Portfolio {
  id: number;
  name?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  categories?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: number;
  title?: string | null;
  image?: (number | null) | Media;
  category?: (number | null) | Category;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'portfolios';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'technologies';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        settings?:
          | T
          | {
              bgType?: T;
              bgGradient?: T;
              bgColor?: T;
              bgImage?: T;
              bgRepeat?: T;
              bgSize?: T;
              bgSizeCustom?: T;
              bgPosition?: T;
              bgAttachment?: T;
              padding?: T;
              maxWidth?: T;
              borderRadius?: T;
              type?: T;
              margin?: T;
              width?: T;
              showMobile?: T;
              mediaBorderRadius?: T;
            };
        richText?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              position?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        featureBlock?: T | FeatureBlockSelect<T>;
        mediaContent?: T | MediaContentBlockSelect<T>;
        mapsBlock?: T | MapsBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        listBlock?: T | IListBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
      };
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              position?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
      };
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              position?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
      };
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
      };
  introContent?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
      };
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlock_select".
 */
export interface FeatureBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
        layout?: T;
      };
  items?:
    | T
    | {
        media?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaContentBlock_select".
 */
export interface MediaContentBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
        gap?: T;
        alignment?: T;
        layout?: T;
        margin?: T;
        width?: T;
      };
  media?: T;
  content?: T;
  enableButtonDirect?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        position?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapsBlock_select".
 */
export interface MapsBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
        width?: T;
        height?: T;
      };
  title?: T;
  specificAddress?: T;
  latitude?: T;
  longitude?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
        type?: T;
        fullWidth?: T;
      };
  title?: T;
  subtitle?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        position?: T;
      };
  slides?:
    | T
    | {
        direction?: T;
        slidesPerViewD?: T;
        slidesPerViewM?: T;
        autoPlay?: T;
        enableArrow?: T;
        items?:
          | T
          | {
              content?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IListBlock_select".
 */
export interface IListBlockSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        bgType?: T;
        bgGradient?: T;
        bgColor?: T;
        bgImage?: T;
        bgRepeat?: T;
        bgSize?: T;
        bgSizeCustom?: T;
        bgPosition?: T;
        bgAttachment?: T;
        padding?: T;
        maxWidth?: T;
        borderRadius?: T;
        layout?: T;
        type?: T;
        iconSize?: T;
      };
  title?: T;
  subtitle?: T;
  items?:
    | T
    | {
        iconContent?:
          | T
          | {
              icon?: T;
              content?: T;
            };
        statsHighlight?:
          | T
          | {
              value?: T;
              label?: T;
              subLabel?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios_select".
 */
export interface PortfoliosSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  icon?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  category?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              placeHolder?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              placeHolder?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              placeHolder?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              placeHolder?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              placeHolder?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  icon?: (number | null) | Media;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label?: string | null;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline' | 'link' | 'secondary') | null;
    /**
     * Choose how the link position should be.
     */
    position?: ('center' | 'right') | null;
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link position should be.
           */
          position?: ('center' | 'right') | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  additionalInformation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  columns?:
    | {
        label: string;
        enableDirectLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          /**
           * Choose how the link position should be.
           */
          position?: ('center' | 'right') | null;
        };
        navItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
                /**
                 * Choose how the link position should be.
                 */
                position?: ('center' | 'right') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyRight?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  icon?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        position?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              position?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  additionalInformation?: T;
  columns?:
    | T
    | {
        label?: T;
        enableDirectLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              position?: T;
            };
        navItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    position?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  copyRight?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  settings: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
    style: 'info' | 'warning' | 'error' | 'success';
  };
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  settings?: {
    /**
     * Select "Image" to use a background image, or "Color" to choose a solid background color. If neither is chosen, the section background will default to transparent.
     */
    bgType?: ('image' | 'color' | 'gradient' | 'transparent') | null;
    /**
     * Enter a CSS gradient value. Supports: "linear-gradient", "radial-gradient", "conic-gradient" (e.g., "linear-gradient(90deg, #fff, #000)". If left empty, section background defaults to transparent.
     */
    bgGradient?: string | null;
    /**
     * Custom CSS color value (e.g., #ffffff, rgb(255,255,255), or color name). Defaults to transparent if left empty.
     */
    bgColor?: string | null;
    /**
     * Upload an image to use as the section background. This image will only be displayed if "Type" is set to "Image".
     */
    bgImage?: (number | null) | Media;
    /**
     * Enable to repeat the background image. When checked, the image will tile to fill the area. Leave unchecked for a single image.
     */
    bgRepeat?: boolean | null;
    /**
     * How the image should scale. "Contain" fits within the area, "Cover" fills it, or set a custom value. Default is auto.
     */
    bgSize?: ('contain' | 'cover' | 'custom') | null;
    /**
     * Enter a value in pixels or percent (e.g., 70px, 50%)
     */
    bgSizeCustom?: string | null;
    /**
     * Choose one or more background positions. Default is center. Example: select "Right" and "Top" to position background at the top right.
     */
    bgPosition?: ('center' | 'right' | 'left' | 'top' | 'bottom')[] | null;
    /**
     * Specifies how the background image scrolls with the page. "Scroll" moves with the content (default), "Fixed" remains stationary.
     */
    bgAttachment?: ('scroll' | 'fixed') | null;
    /**
     * Sets the vertical padding (top and bottom) for the block. Enter values like "40px", "2rem", or "10%". Default is "32px 32px". Leave blank to use the default.
     */
    padding?: string | null;
    /**
     * Set the maximum width for this block. Accepts CSS values such as "40px", "2rem", or "80%". Defaults to "1376px" if left blank.
     */
    maxWidth?: string | null;
    /**
     * CSS border radius for the block (e.g., "16px", "2rem", "50%"). Rounds the corners of the container. Leave blank for no rounding.
     */
    borderRadius?: string | null;
  };
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}